### ISSUE TITLE
Once you've received two shots, the app can show you a "Vollständiger Impfschutz". Even before the two weeks are up.

### ISSUE THREAD

**Issue by felixmaechtle** [Digitaler-Impfnachweis/covpass-android#10]
Hey

## Description
After one received two shots, the app is supposed to show "Vollständiger Impfschutz ab dd.mm.YYYY" for two weeks and a different design. If one forwards the date of the phone for two weeks, the app changes its design and shows "Vollständiger Impfschutz". This might mislead businesses who don't check the QR-Code, which many businesses don't do due to the extra hustle.

Therefore I would suggest that one has to be online at least once after the two weeks are over, so the app can check the current date in an encrypted way via the internet. Similar to Spotify's offline mode where one has to be online once a month.

I tested this Issue on a phone running Android 10 with the CovPass-App Version 0.160.6.

## Steps to reproduce:
 - Import valid European vaccination certificate into the app before the 14 days wait period is over
 - Go to time settings and disable "Use network-provided values"
 - Set the date to some value in the future (more than two weeks)
 - Open the CovPass-App. It displays "Vollständiger Impfschutz" and has a different design.

This is my first issue posted to GitHub, please notify me should this post be missing important aspects of an issue post.

**Comment by Ein-Tim** [comment]
Related to this issue which reports the same "bug" for the Corona-Warn-App: https://github.com/corona-warn-app/cwa-app-ios/issues/2935

**Comment by wkornewald** [comment]
Maybe your suggested solution could be implemented on iOS while Android could get a more general solution that also works for CovPass-Check. Since Android has fewer constraints it should be possible to detect time manipulation more generally even while offline. We’d just need Internet access once on first use of the app and after the phone was turned off for a long time.

**Comment by Flole998** [comment]
This is not really an issue. If you really want to you can take a screenshot of a valid code (14 days passed), replace the code with a not yet valid code (14 days not passed) and be done. Or just show the screenshot which belongs to someone else. So you would have to also add something like a moving border around the code if you want to prevent that. However, the App is open source in the end, so what anybody can do is replace the check, compile it and be done. You could even redistribute the modified App.....

That's why the code must be checked on a device that is known to not have been tampered with. Only then it is possible to check the authenticity and validity of the code. If you trust a device that a person you can not trust has full control over you've lost anyways.

**Comment by zak333** [comment]
As far as I understand, the name, birthday and date of vaccination is encoded and signed by RKI in the QR code. This signature must be validated by the CovPassCheck app of another person who wants to verify the vaccination status. This other person then should **always** match this information **which must be read from the CovPassCheckApp** with the id card of the person. Forgery of a signed code with a different name, date, etc. like taking a screenshot of someone elses code or something should not be possible.

To circumvent the date issue, the vaccination status needs to be checked in the CovPassCheck app as well which should read the vaccination date from the QR code.

The CovPass app of the user can of course give this information as well, but the verification process should always be done by the CovPassCheck app of the person who wants to check the vaccination status.

**Comment by 10Meisterbaelle** [comment]
Businesses should check the QR codes though, it's not that hard

**Comment by jleufgen** [comment]
This is not an error, because if the user changes the system time, CovPass will use the changed system time and show the certificate as valid. However, the CovPassCheck app will identify such a certificate as "invalid".
