### ISSUE TITLE
CovPassCheck variant that does not show type of certificate

### ISSUE THREAD

**Issue by s09bQ5** [Digitaler-Impfnachweis/covpass-android#110]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation
CovPassCheck reports if a QR code is a test certificate or a vaccination/recovery certificate.

## Suggested Enhancement
Add a mode where it is not visible which type of certificate is used.

## Expected Benefits
From Wednesday on we will here in Germany have the situation that employers are required to check if all employees entering the office have a valid vaccination, recovery, or test certificate. While the law allows the employer to record if the employee provided a vaccination/recovery certificate to simplify the check on following days, employers who don't use the information for that purpose don't need it. Since nobody with a vaccination certificate will see the need to perform daily tests to be able to present a test certificate (unless the new IfSG §28b (2) applies), employers would indirectly learn who has been vaccinated and who has not.

**Comment by treysis** [comment]
Those not wanting to disclose that they've been vaccinated can just show the test certificate. Otherwise it will be difficult to differentiate between 2G and 3G. I do understand you want to make vaccination certificates look like they could've also been a test certificate.

Maybe an idea is to use a mode similar to the Austrian GreenCheck app: before you start scanning you have to select which scheme applies (3G, 2G, etc...). If you select 3G it wouldn't differentiate between valid test and valid vaccination certificates and just show a "pass". If you select 2G before scanning it would only validate vaccination certificates, but not test certificates.

**Comment by s09bQ5** [comment]
It's not about vaccinated people not wanting to disclose that they are vaccinated. It is about not-vaccinated people not having to disclose that they are not vaccinated. There is currently a huge amount of social pressure on those who are not vaccinated. I don't really care about those who choose to not get vaccinated. I'm more worried about those who can't get vaccinated because of medical reasons. Do we want to stigmatize them by showing that they are not vaccinated? "Miss X. always shows a test certificate. Is she a Querdenker? Or is she pregnant?"...

I like the idea of having to select between 2G and 3G first. That would also allow the implementation of #107.

**Comment by treysis** [comment]
Why would anyone disclose not being vaccinated by showing a test certificate instead of a vaccination certificate? Even vaxxed people get free tests and many chose to do so.
Whoever has medical reasons to not get vaxxed isn't treated like the general non-vaxxed public (and pregnant people can get vaccinated. It is even encouraged).

**Comment by s09bQ5** [comment]
Sorry, I think I used the wrong term. With test certificate I didn't mean a vaccination certificate used for testing but a certificate proving that someone has been tested.

**Comment by treysis** [comment]
@s09bQ5 yes, me too.

**Comment by jleufgen** [comment]
@s09bQ5 could we close this ticket or is the topic still relevant?

**Comment by s09bQ5** [comment]
Relevant as long as there are things that require only 3G.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
