### ISSUE TITLE
Camera stays active in background even after scan (covpass-check)

### ISSUE THREAD

**Issue by gizmo21** [Digitaler-Impfnachweis/covpass-android#12]
Description

In CovPass-Check the camera stays active scanning in background even after a successful scan was made and an certificate is displayed. 

The camera access is only closed after hitting the x on a certificate.

Steps to reproduce:

Install app access-dots on android so you can see if your camera is used be any app. (similar to a inbuild function iOS has)

This dot get active when you hit scan, but stays even active when certificate is displayed. 

And it only disapears (camera api not accesed) when the x on the certificate is hit

Suggested behaviour:

Camera api should be turned off if cert is found and displayed,  and reactived only if "scan next cert" is hit.
Even if if should be clear that no camera data leaves the device, users could be alarmed that camera stays active in moment it is not needed.

**Comment by sjannevers** [comment]
Thanks for the hint.

The camera is active as long as the scanner view is visible (either complete or behind / over the result bottom sheet).

From my POV this is not a real problem, because
- The camera access is not "hidden", the active camera is visible all the time behind / above the bottom sheet.
- As soon as the scanner view is completely dismissed (by leaving the view or sending the app to background), the camera is not accessed anymore.
- The normal usages of the app is to scan a lot of certificates in a row. By leaving the scanner active behind the bottom sheet, we don't need to reopen the camera each time. Also in theory the camera can already focus the next QR code while checking the last result, to save some time.

**Comment by G00fY2** [comment]
I wouldn't rely on any 3rd party access-dots apps too much. We had similar reports for our apps and it turned out, that there was no issue on our side.

Also Android 12 (currently Beta) has this feature build in. So I would suggest checking if the behaviour also exists on a device running Android 12.

**Comment by gizmo21** [comment]
> I wouldn't rely on any 3rd party access-dots apps too much. We had similar reports for our apps and it turned out, that there was no issue on our side.

True that a third party could report false positives (and even more false negatives) but  sjannevers already acknowledged the reported behaviour and I also reported other app devs who changed their behaviour after report. So Android 12 function is great, but so long access-dots is at least a quite good indicator.

So as devs of CWA do this on purpose, thats fine for me.

**Comment by gizmo21** [comment]
btw. the behaviour seems to have changed in 2.5.1 (family  certificates edition) so issue can be closed as far as I'm concerned.
