### ISSUE TITLE
Reduce flags SVG assets size

### ISSUE THREAD

**Issue by G00fY2** [Digitaler-Impfnachweis/covpass-android#143]
Currently the flag svg drawables (which are only used for 24x24px) images in the country selection view of the validity check are way to large.

Uncompressed file sizes:
- [flag_rs.xml](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/common-app-covpass/src/main/res/drawable-anydpi/flag_rs.xml) - 1600 KB !
- [flag_sv.xml](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/common-app-covpass/src/main/res/drawable-anydpi/flag_sv.xml) - 730 KB
- [flag_do.xml](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/common-app-covpass/src/main/res/drawable-anydpi/flag_do.xml) - 600 KB

## Suggested Enhancement
Replace the large assets (ideally all) with a optimized SVG representations. E.g. the Serbian flag over here has the same details but the file has only 72 KB: https://github.com/hampusborgos/country-flags/blob/main/svg/rs.svg

## Expected Benefits
Smaller APK size, better memory footprint and performance.

**Comment by MikeMcC399** [comment]
@G00fY2 
I also noticed about the large size of `flag_rs.xml` when I reported and looked at the crash issue https://github.com/Digitaler-Impfnachweis/covpass-android/issues/105 in CovPass 1.12.0. I saw that this issue was resolved in 1.13.2.

In the [release/1.13.x](https://github.com/Digitaler-Impfnachweis/covpass-android/tree/release/1.13.x) branch [flag_rs.xml](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/release/1.13.x/common-app-covpass/src/main/res/drawable-anydpi/flag_rs.xml) was reduced in size and I'm now seeing 212KB in 1.13.x instead of 1647KB in 1.12.x (or main).

That still seems excessive for use in a thumbnail size display.

(According to https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/README.md#release-policy-and-branches there may be delays in publishing the released code into the [main branch](https://github.com/Digitaler-Impfnachweis/covpass-android/tree/main) and currently it is lagging behind the version 1.13.3 which has been published to the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.covpass.app&hl=en).)

**Comment by G00fY2** [comment]
It should be way more efficient in size and performance to generate the flags as WebP drawables, because all the vector paths to draw the arms are not visibile at this scale. I just run a short test to see the total size of all flags in 24x24px xxxhdpi PNG -> **218 KB**

**Comment by oliver-steinbrecher** [comment]
Thanks for raising this.  As you already stated we've improved the sizing in release 1.13.2 . There is still room for improvements but it's a matter of priority in comparison to other topics. We're working hard to define the best priorities. Please provide more insights when you experience performance issues with the current app version. Especially share details about your device / setup.

**Comment by pucherd** [comment]
Hello @G00fY2, Thank you for your contribution, this will be part of release 1.40.0
