### ISSUE TITLE
booster certificate not recognized

### ISSUE THREAD

**Issue by btreut** [Digitaler-Impfnachweis/covpass-android#148]
my booster certificate (issued  by Impfzentrum Bayern at Fürstenfeldbruck on 06.12.2021) is not recognized, neither the by corona warn app nor by cov pass nor by cov pass check app.

What should I do?

**Comment by MikeMcC399** [comment]
@btreut 

When you say "not recognized" does this mean nothing happens when you try to scan or do you get an error message?

There is an FAQ article [Why does the CWA not scan a QR code? Why does the QR code scanner not respond?](https://www.coronawarn.app/en/faq/#scan_tips) from CWA covering this topic, which may help.

Otherwise the FAQs from the Impfzentrum Bayern recommend going to a pharmacy to get a replacement certificate or contacting the Impfzentrum. You can look up the telephone number (and address) on https://www.stmgp.bayern.de/coronavirus/impfung/.

**Comment by btreut** [comment]
this is quite strange: My certificate did not show up in the warn-app.  I had already tried the detour by importing a photo and several other methods as suggested in the FAQs, but these did not work. Now retried to scan once again, turning by 90 and 180 deg and got an error message from the warn-app that this certificate was already scanned. Now I see it.

**Comment by btreut** [comment]
it is eventuell more difficult: despite it is my third vaccination and this is noted in the certificate, 
CWA lists this certificate separetly from my other two certificates.  Maybe this is due to the fact that a title is missing in the third certificate.

**Comment by timokoenig** [comment]
@btreut if the name is different, or something is missing, then your only option is to issue a new certificate in the pharmacy.

Regarding the scan problems, I think the team worked on camera adjustments in a newer release that might fix it

**Comment by btreut** [comment]
thanks @timokoenig
