### ISSUE TITLE
Sensitive data from QR code can be scanned without owner's knowledge

### ISSUE THREAD

**Issue by rillig** [Digitaler-Impfnachweis/covpass-android#155]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

The FAQ says:
> Der QR-Code enthält dieselben Daten wie das digitale COVID-Zertifikat der EU. Bei der Überprüfung des QR-Codes mit der CovPassCheck-App werden jedoch nur der Status des Zertifikats, der Name, der Vorname und das Geburtsdatum angezeigt.

The above statement only holds for the official CovPassCheck app, but not for custom-built variants of the same app.

## Technical details

- Device name: any
- OS version: any
- App version: any

## Describe the bug

It is trivial to modify the CovPassCheck app so that it displays not only the name, transcribed name and birthday, but also the other information contained in the QR code.

Assuming that a owner of a CovPass certificate does not trust the user of "the" CovPassCheck app that the CovPassCheck app is indeed the official version that only displays the above-mentioned limited information, how can the owner of the certificate prove that the certificate is indeed valid, without disclosing the sensitive health information from the QR code to the user of "the" CovPassCheck app?

Should the owner of the QR code ask the user of "the" CovPassCheck app for a proof that the app is downloaded from a verified source? And if so, how can the owner of the QR code be reasonably sure that anything shown on the CovPasCheck phone is trustworthy?

## Steps to reproduce the issue

Build CovPassCheck with a modified `CovCertificate.birthDateFormatted` property that shows the sensitive data from the certificate instead of the birth date.

## Expected behaviour

The CovPass app offers different QR codes for typical validation scenarios.
Each of these QR codes is digitally signed and contains only the necessary data for the specific kind of validation.
Alternatively, the sensitive data is encrypted or protected in another way, to prevent unauthorized disclosure.

**Comment by timokoenig** [comment]
@rillig thanks for reporting. This topic has already been discussed in various other tickets. It is a known issue and the topic is in discussion with the EU. I don't have further information on the current state of those discussions but maybe @alexcimander or @molk-ibm know more?
Sadly this topic can't move forward without modifications of the EU COVID Certificate schema. All member states need to agree on a standard that will be used otherwise those certificates will not be valid when traveling in the EU.

**Comment by rillig** [comment]
@timokoenig When I searched for similar tickets, I couldn't find any. They are probably in a different project since they are not specific to Android but are more about the specification. I thought I could add myself as a watcher there. I just wanted to make sure this privacy issue doesn't go unnoticed. Can you point me to these duplicate issues, or are they in some private area?

**Comment by molk-ibm** [comment]
> The CovPass app offers different QR codes for typical validation scenarios.
Each of these QR codes is digitally signed and contains only the necessary data for the specific kind of validation.
Alternatively, the sensitive data is encrypted or protected in another way, to prevent unauthorized disclosure.

As @timokoenig pointed out already, we'd prefer 'view-only' DCCs as well, but I do not support your view that this is a trivial change:
if it is an adhoc operation that should include a short expiration period of such a short lived certificate, we need to include the remote signing service into this process with the consequence that we loose the offline capability.
Right?

**Comment by rillig** [comment]
I never said that the change would be trivial. I just sketched those parts that an end user would see, as an idea of how it might be done, in order to focus on the idea, not the implementation.

Since the specification comes from the EU, there's a whole lot of work needed behind the scenes. I agree that for ad hoc short-lived certificates, an online service would be needed. But that's only one way to implement the idea, maybe there are others as well.

**Comment by molk-ibm** [comment]
how else should the signature be applied?

**Comment by timokoenig** [comment]
There are multiple major challenges that needs to be talked about and implemented.

* First of all this needs to be part of the EU specification so that every member state can implement this change.
* There needs to be an online service that creates those certificates otherwise we can not create a trusted signature.
* We might have a data privacy issue less with certificates that do not contain all information but now we have another data privacy issue because the users certificate leaves the smartphone and gets send to the new backend service.
* All German states currently come up with new rules what needs to be checked to be considered valid. This makes this whole feature very difficult because what exactly is not needed from the current DCC? I would guess there are just one or two fields that are not needed (at the moment) that could be removed in the "light" certificate.
* There are two possibilities of certificates that could be created.
** One is a "light" certificate that contains less information than the original DCC but as described before this is more and more difficult because almost everything is needed.
** The second option would be a short-lived validation certificate that just says "This person xxx born on xxx is considered valid". There we have a bigger implementation effort in the backend service because we need to validate the whole certificate based on the venue that the user wants to enter. This sounds great but we would loose the offline functionality that is needed in a lot of places due to the lack of internet connectivity.

I could go on and on with things that needs to be considered when implementing this feature but without EU effort this does not make sense

@rillig I will look for the other tickets later and link them here

**Comment by MikeMcC399** [comment]
I don't know if you are aware of https://www.coronawarn.app/en/faq/#val_service which also mentions the CovPass-App.

That FAQ article links to
https://ec.europa.eu/health/sites/health/files/ehealth/docs/covid-certificate_traveller-onlinebooking_en.pdf
and to
https://github.com/eu-digital-green-certificates/dgca-validation-service.

This splits the validation service, which has full access to certificate details, from the consumer of the information (event manager, airline, etc.) who only gets the result of the check, not the details of the certificate itself.

It may be relevant for this issue to know what is going on in this other area. (If not, then I apologize in advance for the interruption!)

**Comment by wkornewald** [comment]
If you're willing to give up offline validation then a normal online validation service could work - even if the primary use-case is for validation on websites.

The other possibility is to use a different kind of online validation service that generates a signed result which is valid for e.g. 12h, so you could open the app in advance when you have Internet to load the signed result and then enter some offline area and still get validated. Not perfect, but maybe good enough as a trade-off?

However, you'd have to trust the online service (which could maybe use Intel SGX to provide a pretty high level of privacy). Also, you could still use the full offline capable cert as a fallback.

**Comment by timokoenig** [comment]
I was talking more about the day to day use of CovPass Check and not only the travel or booking use cases. It's good that we have a service that allows the integration but I think the user is interested in a better solution that provides more privacy in their daily DCC checks.

Maybe this service can be extended to create those signed results for our CovPassCheck? Not sure if this has been discussed on a EU level. But I think another problem here is that the validation service uses the EU rules which do not apply for all German states therefore we need to have another ruleset

**Comment by moabits** [comment]
Cross-ref
* iOS issue https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/66 
* EU Spec https://github.com/ehn-dcc-development/hcert-spec/issues/107 and

**Comment by BengtHagemeister** [comment]
The dutch system is build with these concerns in mind. There are 2 different QR Codes: One for international travel and one for inside The Netherlands only. The dutch QR Code has way more privacy features build in, to name a few: 
- 30 seconds short live QR Code to make tracking across different locations impossible
- Only the first letter of the first name, last name and birth month, birth date is shown (and one of these is randomly not shown, this changes randomly with the short live QR)
- There is no information on the Vaccination, Recovery, Test. Only if valid or not valid.

Here are a few links to the Dutch FAQ for more information: 
- https://coronacheck.nl/en/faq/1-6-welke-informatie-staat-in-mijn-qr-code/
- https://coronacheck.nl/en/faq/1-7-werkt-de-coronacheck-app-ook-offline/
- https://coronacheck.nl/en/faq/1-1-hoe-werkt-de-coronacheck-app/

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
