### ISSUE TITLE
Issue | Camera not Opening Galaxy A5 2017 

### ISSUE THREAD

**Issue by SamsungHandy** [Digitaler-Impfnachweis/covpass-android#177]
So on the app the camera isn't opening 

->black screen also flash isnt working but it's working in other apps 
I'm on custom rom

**Comment by MikeMcC399** [comment]
@SamsungHandy 

What operating system are you using on your Samsung Galaxy A5 (2017)?

CovPass version 1.16.1 running on Samsung Galaxy A5 (2017) SM-A520F with Android 8.0.0 is able to open the camera and successfully scan a vaccination certificate.

**Comment by memartinb** [comment]
Possibly related to #114? Having issues as well on S5 mini (G800F) with LineageOS 16 (Android 9).

**Comment by pucherd** [comment]
Hello @SamsungHandy, @memartinb, are you still experiencing this issue in version 1.30.0? We did some minor improvements in this version.

**Comment by MikeMcC399** [comment]
@pucherd 

I suggest to close this issue because there hasn't been any response from the original poster @SamsungHandy since their original problem report which was nine months ago.

They said they were on a custom rom, however did not provide any further details.

I checked once again on Samsung Galaxy A5 (2017) SM-A520F with Android 8.0.0 and the latest CovPass version (1.31.0) and there was no problem to scan a certificate with the camera.

**Comment by SamsungHandy** [comment]
Hi, 
You can close this ticket as I don't have this phone anymore it broke down 

-it was a galaxy A5 2017 
With Samsung os port 
Android 9?? 

->it was my phone then I gave it to my brother he used it with this rom

**Comment by memartinb** [comment]
Camera is opening with v1.30+, but very slow and stuttering. Can't scan the QR Code.
But my device is kminilte/G800F.
