### ISSUE TITLE
Distribute the app via F-Droid too

### ISSUE THREAD

**Issue by jugendhacker** [Digitaler-Impfnachweis/covpass-android#2]
This is kind of a followup to Digitaler-Impfnachweis/documentation#8. I started to track the integration of this app into the [F-Droid repository](https://f-droid.org/) over at [their issue tracker](https://gitlab.com/fdroid/rfp/-/issues/1769).

For now I would like to know if this is generally supported by RKI and/or IBM? And if yes, could you provide a short summary of the app (max 80 chars) and a longer description which should/could appear on the F-Droid site?

**Comment by wkornewald** [comment]
This would indeed be nice. The decision is still pending though. Also, reproducible builds are another open question.

**Comment by jugendhacker** [comment]
@wkornewald reproducible builds would of course be the best option for F-Droid, because then they could distribute exactly the same APK with the same Signature as on the Playstore and just verify if it was correctly build from source.

**Comment by petrarca-arezzo** [comment]
Absolutely; I really want to see CovPass on F-Droid, which I assume shouldn't be a big issue to accomplish...

**Comment by Rechts** [comment]
Ja, in F-Droid als AKP File UND für Android 5 ! Warum soll ich die Wegwerfindustrie unterstützen? Mein Handy ist jünger, als alle hier! Wetten!

**Comment by jugendhacker** [comment]
@Rechts I'm not the maintainer of this repo, but usually it's not that nice to clutter up issue with offtopic comments and/or with comments without any helpful content.

**Comment by bitfasching** [comment]
Hi all, any news on that topic?

Having the app on F-Droid would make it accessible to privacy-minded people who are unable or unwilling to build it themselves. Getting it from a trustworthy source other than Google is difficult right now, especially since it seems to be hidden from users outside Germany. Taking Aurora Store as a popular example of an alternative to Google's Play Store, it uses anonymous accounts from random locations to access the app index, which means that [the app won't show up and can't be installed](https://gitlab.com/AuroraOSS/AuroraStore/-/issues/668).

**Comment by Flnch** [comment]
I cannot provide you with news on this topic, but as I described [here](https://gitlab.com/AuroraOSS/AuroraStore/-/issues/668) it is at least possible to install the app using the Aurora Store, but without a Google Account.

**Comment by fridlmue** [comment]
Are there any assets or names that we would need to strip when forking this project and releasing binaries on github releases and f-droid to not violate some license or trademarks?

**Comment by wkornewald** [comment]
> 
> 
> Are there any assets or names that we would need to strip when forking this project and releasing binaries on github releases and f-droid to not violate some license or trademarks? (at least I did not find a 'NOTICE' file somewhere)

Why do you want to fork this project instead of contributing to the official one?

**Comment by fridlmue** [comment]
> Why do you want to fork this project instead of contributing to the official one?

I really don't want. So if it is not a problem to self host publicly a binary or binary repo with a self compiled version of the covPass app (including all assets and names) i would also go that way. If it is not, i need to know which components to exchange to not violate some property rights.
But in fact I'm only missing a F-Droid Release or a official distribution of the apk-File on some website or github releases. But as long that is not fulfilled people are asking for a .apk, because they do (intentionally) not use Google Services. And I'm willing to provide those who ask a binary for that. (Not from a shady source like apk-pure or alike, and the AURORA workaround is ok, but not really a solution.)
As CovPass support told this is not done due to some obscure "security reasons", I'm going to provide that at least for people who ask me for a hint how to install it.

**Comment by mar565** [comment]
Any news on this?
@fridlmue you forked the project a week ago. Did I miss the .apk or is it WIP?

**Comment by mythsunwind** [comment]
> This would indeed be nice. The decision is still pending though. Also, reproducible builds are another open question.

Any news on the decision? Does the original app author oppose the inclusion to F-Droid?

**Comment by jugendhacker** [comment]
@wkornewald as this issue is now a month old and together with @mythsunwind we got almost everything ready for F-Droid inclusion what we can to from our side, I would like to now what's the current status about it internally at IBM and RKI? Will F-Droid inclusion be supported and will IBM/RKI provide a short summary about what the app is, a long description of what the app does and screenshots or should we care about this ourselves and do this completely independent of IBM/RKI?

**Comment by olof-nord** [comment]
Any news on this issue? I would really like to install this from F-Droid and not from Google, as this is slowly becoming a requirement as someone living in Germany.
What can I do to assist in this process - and is there a roadmap for the pending decision?

**Comment by ilf** [comment]
Yes, please, what can the community do, what's missing to get this done?

**Comment by JensTheCoder** [comment]
Switzerland provides their Covid Certificate app through F-Droid:

https://f-droid.org/en/packages/ch.admin.bag.covidcertificate.verifier/

The EU also is standing for freedom, and that is what Open-Source means.

My vote here in this comment for providing the EU Covid Certificate app through F-Droid.

**Comment by JensTheCoder** [comment]
This is what the CovPass support team replied to the question, why the app isn't available at the open source app store F-Droid.

-------- Forwarded Message --------
Subject: Re: CovPass
Date: Tue, 27 Jul 2021
From: Support <support@covpass-app.de>

Sehr geehrte Damen und Herren,

danke für Ihre Anfrage zur CovPass-App und die Frage nach Alternativen zu einem Download aus den bekannten App Stores.

Tatsächlich gibt es keine Alternativen, und zwar insbesondere aus Sicherheitsgründen und um Missbrauch vorzubeugen. Sollten Sie keine Möglichkeit zum Download haben, können Sie auch immer das ausgedruckte Impfzertifikat in Kombination mit einem Ausweisdokument als Impfnachweis nutzen.

Wir hoffen, Ihnen hiermit geholfen zu haben. Für weitere Fragen helfen sicher auch die FAQ auf https://digitaler-impfnachweis-app.de/faq/.

Sollten Sie Hilfe bei der Nutzung der CovPass-App benötigen, wenden Sie sich gerne an unsere Hotline 0800 47 47 001.

Mit freundlichen Grüßen
das Support-Team der CovPass-App
Im Auftrag des Robert-Koch-Instituts
Nordufer 20 | 13353 Berlin
Folgen Sie uns auf Twitter: @rki_de

Das Robert Koch-Institut ist ein Bundesinstitut im Geschäftsbereich des Bundesministeriums für Gesundheit

**Comment by JensTheCoder** [comment]
26. Juli 2021, 14:13 Uhr
Cloud-Computing: Wie Europa die Abhängigkeit von den US-Techkonzernen verringern will

https://www.sueddeutsche.de/wirtschaft/cloud-eu-gaia-x-open-source-1.5363726

So, guys, then just do it. Make your app available at open source app stores. Like the EU is telling us.

**Comment by ilf** [comment]
> This is what the CovPass support team replied to the question, why the app isn't available at the open source app store F-Droid.

Thanks, but that's a non-answer from first-level-support.

**Comment by jugendhacker** [comment]
> This is what the CovPass support team replied to the question, why the app isn't available at the open source app store F-Droid.

Looks like the support did not get exactly the point you asked them about. But AFAIK they are not really there to help you with this topic. This is why this issue exists. But it would be nice if we all could just stay calm and wait for IBM/RKI officials to respond instead of filling up this issue with off-topic links and messages about e.g. the open source strategy of the EU.

**Comment by jugendhacker** [comment]
@ilf @olof-nord 
> Yes, please, what can the community do, what's missing to get this done?

From the F-Droid (and so community) side more or less everything is already done. Together with @mythsunwind we already prepared [a MR over at the F-Droid build metadata repository](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9360). Now we are just waiting for IBM/RKI to maybe provide screenshot, description and summary. If they are not willing to provide them, we'll just go with the ones from the Playstore.

**Comment by ilf** [comment]
@jugendhacker: IMHO F-Droid should go ahead, use (screenshot|description|summary) from Playstore and ship the app. If IBM/RKI want to change (screenshot|description|summary), that can be done easily. But we've waited six weeks and I don't see why we should wait longer, especially since there is no ETA.

**Comment by jugendhacker** [comment]
@ilf Yeah I would say let's wait until the end of the week or so, maybe @wkornewald or someone else from the IBM/RKI team will come up with an ETA and if not I think it's time to go on and just do it on our own as community. Luckily the app is FOSS and everyone has the right to distribute builds of it.

**Comment by obfusk** [comment]
F-Droid requires that "The original app author has been notified (and does not oppose the inclusion)" (though I'm not entirely sure how "hard" that requirement is). Even if no reply could be construed as "does not oppose", I'd prefer to get some kind of OK.

It would also be nice to get reproducible builds if possible for extra security.

Feel free to ping me if I can help with anything related to F-Droid (or reproducible builds) :)
(I'm an F-Droid core contributor; I also speak German; but I don't live in Germany myself.)

**Comment by mythsunwind** [comment]
> Feel free to ping me if I can help with anything related to F-Droid (or reproducible builds) :)

In the [merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9360#note_622806897) we were unsure how to deal with the versionCode (use versionCode calculation from upstream which has to be done manually on every new version or do versionCode updates like other f-droid apps). Maybe you can help us there and clear things up in the merge request?

**Comment by wkornewald** [comment]
First of all, thanks everyone who tries to contribute despite the slow decision process.

@obfusk once we have a decision we'll surely get in touch, thanks!

@mythsunwind Would it be possible to automate this using a simple script? We could also move the calculation of the versionCode into a separate script in our repo, so you can easily reuse that and build some automation script for F-Droid. In the end, the goal should be to automate the whole deployment as much as possible.

**Comment by obfusk** [comment]
> Would it be possible to automate this using a simple script? We could also move the calculation of the versionCode into a separate script in our repo, so you can easily reuse that and build some automation script for F-Droid. In the end, the goal should be to automate the whole deployment as much as possible.

The update check is not allowed to run arbitrary code. Providing a file with the version code in the repo would be nice (but maybe not ideal for you). Having a url we can scrape w/ a regex for the latest version + versioncode is also supported. We are looking into supporting a calculation using #commits+offset but that would have to be implemented first.

**Comment by obfusk** [comment]
> I'll have to check what this update check is doing exactly, but what about just adding a reference to the official Play Store entry for the update check? The commits+offset thing is unreliable because we sometimes have to increase the offset and ideally we'd rather build this whole versionCode thing on top of what we already have in the Fastfile where we can just increment based on the latest version in the Play Store. (edit: the complexity here is that the deployment happens in a separate, secured environment)

AFAIK you can't get the versioncode (e.g. `418`) from the play store, just the version (e.g. `1.38.0`).

Documentation: https://f-droid.org/en/docs/Build_Metadata_Reference/#UpdateCheckMode

**Comment by Jowat97** [comment]
> @ilf Yeah I would say let's wait until the end of the week or so, maybe @wkornewald or someone else from the IBM/RKI team will come up with an ETA and if not I think it's time to go on and just do it on our own as community. Luckily the app is FOSS and everyone has the right to distribute builds of it.

I think it would be fine to go for it. F-Droid only requires, that the "_original app author has been notified and does not oppose the inclusion_". And both of those requirements were met. In addition, this App is released under Apache 2.0 License:
`You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form.`

So that shouldn't be a problem at all. And the Corona Contact Tracing App, which has implemented the exact same feature, is already available in the F-Droid Store. The metadata can be taken from the Play Store. And if they want to change it, they can add it to the repository. It shouldn't fail because of that.

We even don't have an ETA. It is better to have this App now, without some metadata like Screenshots, than having no App at all.
People, who refuses to use Google Services, shouldn't be punished therefor. This App is funded by the public and published under a free license. So it should be free and public as well. Especially, since this app is your ticket to get back a normal life.

**Comment by jugendhacker** [comment]
Just for those who might have subscribed this issue: through community work [CovPass](https://f-droid.org/de/packages/de.rki.covpass.app/) and [CovPassCheck](https://f-droid.org/de/packages/de.rki.covpass.checkapp/) did still make their way into the F-Droid store based on a fork which could be found [here](https://gitlab.com/covpass-android-foss/covpass-android/)
