### ISSUE TITLE
Error 902: at "Update entry rules" ("Einreiseregeln aktualisieren") ...

### ISSUE THREAD

**Issue by Jo-Achim** [Digitaler-Impfnachweis/covpass-android#200]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name:  Samsung Galaxy Note 10, SM-N970F/DS
- OS version:  Android 12 (One UI 4.0)
- App version:  1.21.0

## Describe the bug

After tapping "Update" under "Update Entry Rules", the entry rules appear to be updated. At least that's what the data under "Last Update" suggests. The data displayed there correspond exactly to the current date and time.

However, immediately followed by the message:

> Sorry
> An unexpected error has occurred. Please try again later. (Error 902)

However, trying "try again later" gives the same result. Updating the data under "Last update" followed by the error message "Error 902". 

## Steps to reproduce the issue

1. Open the app
2. Goto 'Information'
3. Tab on 'Update Entry Rules'
4. Tab on 'Update'

## Expected behaviour

Is the error message correct? If so, it probably shouldn't appear. 

## Additional context

The error message has been appearing for over an hour. Restarting the app does not solve the problem.

**Comment by MikeMcC399** [comment]
I can reproduce this issue.
In the app source it looks like this would be
`public const val ERROR_CODE_GENERAL: Int = 902`
so the error code looks like it is unspecific.

**Comment by pucherd** [comment]
Hello @MikeMcC399, thank you for reporting this bug -> we will release 1.21.1 hotfix asap.

**Comment by MikeMcC399** [comment]
@pucherd 
It's good to hear that there will be a hotfix soon. Thanks also to @Jo-Achim for making the original discovery and reporting it. I would not have noticed the issue without his report.

**Comment by MikeMcC399** [comment]
- As mentioned in another unrelated topic (https://github.com/Digitaler-Impfnachweis/covpass-android/issues/97) Error 902 also occurs in CovPassCheck 1.19.0 when executing "Update rule set".
- @puchard: Regarding your feedback: This is not a hard error. Sometimes it occurs, sometimes it does not. I just tried it on CovPassCheck 1.19.0 and I'm getting an error.

**Comment by MikeMcC399** [comment]
@pucherd 

On a device where CovPassCheck 1.19.0 was giving Error 902 I re-installed the app and the error disappeared. I have one other device left where I didn't re-install and this device is giving Error 902 consistently.

**Comment by MikeMcC399** [comment]
I deleted CovPassCheck 1.19.0 app data (rather than re-installing the app) on the device which was still producing Error 902 and the error message no longer appeared when executing "Update rule set". This workaround is only effective for CovPassCheck 1.19.0. It does not workaround the problem for CovPass 1.21.0.

**Comment by Jo-Achim** [comment]
@MikeMcC399 wrote: 
> I deleted CovPassCheck 1.19.0 app data (rather than re-installing the app) on the device which was still producing Error 902 and the error message no longer appeared when executing "Update rule set". This workaround is only effective for CovPassCheck 1.19.0. It does not workaround the problem for CovPass 1.21.0.

Correct.
So we will wait to 1.19.1.

**Comment by hitd010000** [comment]
In CovPass 1.21.0 it seems that this bug still exists and occurs on 2 places:
-verify (Gültigkeit prüfen) (maybe start actualisation of entry rules in background?)
-update entry rules (Einreiseregeln aktualisieren)  (via menu available by click ?)
I've updated my custom ROM yesterday to Android 11 from Android 10. Therefore has to reinstall CovPass.

Maybe caused by sequence of scan of certs?
I've scaned first booster cert (3 of 3, direct available to show as paper) and after that (because stored in archive) 2 of 2 from basic vaccination process.

However: last actualisation of entry rules is shown correct. It seems like this is done fine. After start this Error 902 occurs, reporting to be repeat "process later again", but date and time of "Liste der Zerifikatsausteller" (list of cerificate authorities) and "Einreiseregeln" (entry rules) changed to current date and time. If process of update fails, i think date and time should not changed if data are not updated in reality?

hth
Peter
Samsung Galaxy Note 3
[ROM][OFFICIAL][11] LineageOS 18.1 for Samsung Galaxy Note 3 (hlte*)
rooted device magisk 24.1

**Comment by MikeMcC399** [comment]
@hitd010000 
See https://github.com/Digitaler-Impfnachweis/covpass-android/issues/200#issuecomment-1083546585 where it says there will be a CovPass 1.21.1 hotfix for this issue. I don't know what the expectations for the meaning of "ASAP" are. The information was 5 days ago.

**Comment by Jo-Achim** [comment]
In **CovPassCheck 1.19.1** the bug seems to be fixed.
And in **CovPass 1.21.1** the bug doesn't seem to exist anymore either.

**Comment by MikeMcC399** [comment]
@Jo-Achim 

> In **CovPassCheck 1.19.1** the bug seems to be fixed. And in **CovPass 1.21.1** the bug doesn't seem to exist anymore either.

Thanks for the tip!

It seems that the new versions were only made available just a few minutes ago.

https://play.google.com/store/apps/details?id=de.rki.covpass.app&gl=DE
https://play.google.com/store/apps/details?id=de.rki.covpass.checkapp&gl=DE

**Comment by MikeMcC399** [comment]
@Jo-Achim 

I cross-checked and see no problem with the hot-fixed versions:

App | Function | Version
--- | --- | ---
CovPass | Update rules of entry | 1.21.1
CovPass Check | Update rule set | 1.19.1

I guess you could close this issue now! 🙂

**Comment by Jo-Achim** [comment]
Closed.

**Comment by hitd010000** [comment]
@MikeMcC399 
I only tried to help.
I've 1.19.0 and 1.21.0 on the same phone. 1.21.0 throws error 902, 1,19.0 doesn't.

I've got this 902 error and because no useful explentation of error 902 i searched for it. I found this conversation here and only tries to give additional informations so developers are able to find the bug.

In general, the issue occurs ALSO on Android 11 ( original report is for Android 12 ), even if not started "update enty rules" (Einreiseregeln aktualisieren) manualy, but by default on a automatic way only by trying to "check if valid" ("Gültigkeit prüfen").

Peter

**Comment by MikeMcC399** [comment]
@hitd010000 
> I only tried to help.

All help is appreciated! It seems if you now go to the Google Play Store you will be able to get an updated version of both apps. If you could let us know if the hotfix versions solve the problem, that would be a great confirmation. Thanks!
