### ISSUE TITLE
No option for certificate renewal in Version 1.26

### ISSUE THREAD

**Issue by T-F-S** [Digitaler-Impfnachweis/covpass-android#212]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung S10+
- OS version: Android 12
- App version: 1.26.0

## Describe the bug

Version 1.26 should contain the functionality for certificate renewal.
In https://github.com/Digitaler-Impfnachweis/covpass-android/issues/207#issuecomment-1149806209 already was observed that after update to 1.26 there is no "Renew vaccination certificate" button.

However, killing the app and restarting the phone does not do the trick on my device. So, even after complete restart, CovPass 1.26 has no certificate renewal functionality on my device.

I have two certificates which expire soon and need to be renewed. My third one is valid for a longer period. Maybe, this is the reason for the bug, i.e. the valid certificate *may* block the two other ones for renewal?

**Comment by Ein-Tim** [comment]
> I have two certificates which expire soon and need to be renewed. My third one is valid for a longer period. Maybe, this is the reason for the bug, i.e. the valid certificate may block the two other ones for renewal?

You could test if this is the _problem_ by deleting the third certificate. To me this all sounds intentionally, as this is also the behavior of the Corona-Warn-App. Only the newest certificate needs to be reissued, see [CWA 2.23: Extension of technically expired certificates in the CWA](https://www.coronawarn.app/en/blog/2022-06-01-cwa-2-23/) which says:

"**Recovery certificates** can always be renewed when they are about to expire technically. For **vaccination certificates**, users only need to renew the certificate currently in use, as it contains sufficient information about vaccination protection. For users who have stored three vaccination certificates in the CWA, this means that the vaccination certificate of the first and second vaccination will not be exchanged, but only the vaccination certificate of the booster vaccination as soon as it is about to expire."

**Comment by T-F-S** [comment]
> You could test if this is the _problem_ by deleting the third certificate. To me this all sounds intentionally, as this is also the behavior of the Corona-Warn-App. Only the newest certificate needs to be reissued, see [CWA 2.23: Extension of technically expired certificates in the CWA](https://www.coronawarn.app/en/blog/2022-06-01-cwa-2-23/) which says:

If this is the intended behaviour, then the showed text of the app when selecting the older certificates is very misleading. I cannot take screenshots of CovPass in Android, but the text says:

"Sie können das Zertifikat bequem in der CovPass-App austauschen. Nutzen Sie dafür die Erneuerungsfunktion in der Übersicht der Zertifikate oder scannen Sie ein neu ausgestelltes Zertifikat ein".
If only the newest certificate can/should be renewable, why does the app promote renewal for all certificates (but does not provide it).

I hesitate to delete my third certificate (never change a running system), but I will try to get hand on another phone where I only scan my older certificates to see, if I can renew them there.

**Comment by Ein-Tim** [comment]
@T-F-S 

I agree with you, if the behavior you see is intended, the text is incredible misleading!

**Comment by adeuring** [comment]
I'm having the same problem: Two certificates will expire on June 12th; the covpass warns me about the imminent expire date, and I have a more recent certificate for the third vaccination.

If the app "thinks" that older certificates do not need to be renewed, it should not warn about the expiration. In this case I'd call the app's behaviour a quite insane UI bug.

And this bug - be it a plain UI bug, be it a implementation bug (assuming that it could also be intended to support the renewal not only of the most recent certificate) seems to be a bit costly too: I called the hotline and they told me that they got a number of calls on this topic today...

Another question: Why came this update so late? It was obvious since more than a year that certificates will begin to expire in may/june of this year. Was it really necessary to publish the renewal feature so late?

**Comment by Ein-Tim** [comment]
Did anyone check the behavior under iOS? I can't sadly. cc @timokoenig

**Comment by T-F-S** [comment]
I can now confirm that only the newest certificate is offered to be renewed. If the current valid certificate is removed, the newest invalid certificate can be renewed (but ONLY this one).

So, for 3 certificates the following works:
- Remove "Impfung 3 von 3" and "Impfung 2 von 2" such that only "Impfung 1 von 2" remains.
- Fiddle around (closing/starting/killing/...) with the app until renewal is possible. Renew "Impfung 1 von 2".
- Scan "Impfung 2 von 2"
- Fiddle around (closing/starting/killing/...) with the app until renewal is possible. Renew "Impfung 2 von 2".
- Scan "Impfung 3 von 3" (no renewal necessary in my case).
- Export renewed certificates as PDF

IMHO this procedure should be possible with one or two clicks inside the CovPass without the clumsy workaround. Or, the app should not display warnings for old certificates, if they *really* are not important (today, tomorrow, the coming COVID autmn, ...)

**Comment by Ein-Tim** [comment]
Okay, so the real bug here is the misleading UX/UI.

**Comment by timokoenig** [comment]
@Ein-Tim true but on the other hand this is not even a full vaccination therefore kinda useless

**Comment by adeuring** [comment]
Here is a "screenshot" [1]: 
![IMG_0407](https://user-images.githubusercontent.com/6950346/172644504-6bfbbaa5-7791-4bc4-a91e-545b9e639aed.JPG)

So... The claim that I can renew the certificate is plain wrong – be it because it's not necessary (in rgar case the message should not appear at all), or the renewal feature is broken.

On, and BTW: Notice the time format: "12:36 nachm." Why not "23:36"? My phone is configured for a German UI, and the app seems to "see" that as it translates "pm" to "nachm.".

A weird mix of US/English time format with the date format dd.mm.yyyy which does not look not that US/English.


[1] another, erm, stumbling point: The Covpass app does nor allow to make screenshots, so I had to use a camera... What is so confidential about Covpass that it needs to prevent screenshots?

**Comment by Ein-Tim** [comment]
> What is so confidential about Covpass that it needs to prevent screenshots?

See https://github.com/Digitaler-Impfnachweis/covpass-android/issues/62. IMO this restriction makes no sense at all as it can be bypassed by saying "OK Google, take a screenshot". Tada, there you have a screenshot of CovPass. Restricting screenshots is probably a _security_ measure which was installed by BSI. CWA also had such a _feature_ at the very start, but soon after the community complained, the restriction was removed.

**Comment by MikeMcC399** [comment]
- Since this issue has got a little complicated with a mix of different problems, I opened a new issue to concentrate on the text message. See #215.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> If this is a staged rollout, I suggest to pause it and prepare a hot fix. If this is not a staged rollout, a hot fix addressing the issues listed above should be prepared as soon as possible.

Accessing https://play.google.com/store/apps/details?id=de.rki.covpass.app via web browser in incognito mode shows version 1.26 so that means there is no on-going roll-out. The roll-out is complete and there is no going back, only going forward.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thank you for the information!

> there is no going back, only going forward.

That's a good motto (: Let's stay positive & hope that the developers have a hot fix ready soon.

**Comment by alexcimander** [comment]
Hey everyone,
we are aware of the current issues and we are currently working on a fix.
- For Vaccinations only the "most recent" Vaccination (when it comes to date of vaccination) can be renewed if (about to be) expired. 
- For recoveries the re-issue will be offered for all of them when they are (about to be) expired. 

Thank you for the reports and discussion - bear with us - we are on it!

**Comment by MikeMcC399** [comment]
@alexcimander 

The UI issues for renewals make the use of the app confusing. It's good to hear that you are working on fixes.

It's also confusing that the FAQs on https://digitaler-impfnachweis-app.de/en/faq (English and German) have not been updated. For instance the following implies that certificate renewal is not yet possible:

![image](https://user-images.githubusercontent.com/66998419/172789384-c951afc0-8f7e-41d7-bed2-21d497220532.png)

In German it says: "Die dazu notwendige Neuausstellung können Sie demnächst in der App mit wenigen Klicks selbst durchführen."

**Comment by Ein-Tim** [comment]
@T-F-S 

Please check if the UI has sufficiently improved with version 1.26.1.

**Comment by timokoenig** [comment]
Text still indicates that the certificate can be renewed but it can't because there are newer certificates. I would suggest to leave this open

**Comment by MikeMcC399** [comment]
@timokoenig 
> Text still indicates that the certificate can be renewed but it can't because there are newer certificates. I would suggest to leave this open

What text are you seeing?

If I scan 1/2, 2/2 and 3/3 vaccination certificates, where the 1/2 certificate is due to expire in the next 28 days, the 1.26.1 app displays the following text for the 1/2 vaccination certificate:

"If this is your latest certificate, you can renew it on the overview of your certificates. Otherwise, you don't have to do anything because your latest certificate contains all the necessary information for a check."

The German text is:

"Wenn es sich hierbei um Ihr neuestes Zertifikat handelt, können Sie es auf der Übersicht Ihrer Zertifikate erneuern. Andernfalls müssen Sie nichts tun, da in Ihrem neuesten Zertifikat alle notwendigen Informationen für eine Prüfung enthalten sind."

- The text changes were done by PR https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/pull/213.

- I think that is consistent now, which is the reason that I already closed issue #215 since it is solved in 1.26.1

**Comment by MikeMcC399** [comment]
The text

"If this is your latest certificate, you can renew it on the overview of your certificates. Otherwise, you don't have to do anything because your latest certificate contains all the necessary information for a check."

and

"Wenn es sich hierbei um Ihr neuestes Zertifikat handelt, können Sie es auf der Übersicht Ihrer Zertifikate erneuern. Andernfalls müssen Sie nichts tun, da in Ihrem neuesten Zertifikat alle notwendigen Informationen für eine Prüfung enthalten sind."

could be slightly improved. The second sentence sounds like you have a choice about doing something, whereas you do not because there is no renewal button available.

---

To be accurate and clear it would have to say something like :

- "... You cannot renew earlier certificates. Your latest certificate contains all the necessary information for a check." (EN)

- "... Sie können frühere Zertifikate nicht erneuern. In Ihrem neuesten Zertifikat sind alle notwendigen Informationen für eine Prüfung enthalten." (DE)

**Comment by adeuring** [comment]
I agree with MikeMcC399 that the new message is much better. But still:

The app obviously knows that the first two, expired or soon expiring, certificates do not need to to be renewed as it does not offer to do that. Why can't this "knowledge" be used to show a clear message like "Since you have a more recent certificate for a more recent vaccination, there is not need to renew this outdated (obsolete?) certificate"?

**Comment by MikeMcC399** [comment]
In CovPass 1.27.0 the text now says "Previous certificates will not be renewed.", so that is clearer than it was before.

**Comment by adeuring** [comment]
Right, this is better than before. But still: If the app can make a decision for which certificates to offer a renewal, then it can use the very same "decision mechanism" to show a clear message, like "This certificate is expired but is does not need to be renewed and it cannot be renewed because your certificate(s) from <some date> are more recent, still valid, and they are sufficient to prove your vaccination status where needed."

**Comment by MikeMcC399** [comment]
@adeuring 

>  If the app can make a decision for which certificates to offer a renewal, then it can use the very same "decision mechanism" to show a clear message, like "This certificate is expired but is does not need to be renewed and it cannot be renewed because your certificate(s) from are more recent, still valid, and they are sufficient to prove your vaccination status where needed."

The text in 1.26.1 is "You can easily renew your latest certificate in the CovPass app. Previous certificates will not be renewed. To do so, use the renewal function in the overview of your certificates or scan a newly issued certificate."

https://github.com/Digitaler-Impfnachweis/covpass-android/blob/d2304e1c1281ddb048b3896f3a46802cb5bf278d/common-app-covpass/src/main/res/values/generated_strings.xml#L395

I think what you are proposing would need to be a separate enhancement request as it is not the same as the original issue here. I can definitely see the value of a different text depending on whether the certificate in question, which is about to expire or has already expired, is actually the latest certificate or not.

**Comment by adeuring** [comment]
MikeMcC399, you are probably right that my point is in a very strict sense a separate issue. But frankly, I don't see the point to nag developers in that way. If these folks just fix an issue in the most simple way possible, in this case by only changing a static message, without thinking a bit further regarding usability or clear messaging, there is, I'm afraid, a deeper problem: Nobody in the whole chain of command, from Bundesgesundsheitsministerium or Robert-Koch-Institut via the contracting companies (IBM and/or Ubirch, I assume) down to individual developers seems to really care about simple usability issues. I am not sure if or how this problem can be described in a Github issue ;)

**Comment by Staeffy** [comment]
Hello everyone, 
thanks for your feedback and lively discussions here! 
We do care about simplicity and usability. However, unfortunatelly, we also have time & cost constraints and need to deal with often changing requirements. 
Therefore, we try to hard code as little app logic as possible, so that we are more flexible when it comes to changing requirements in the future. 

We discussed the options we have on messages to be displayed very detailed and agreed, that there are just too many options to cover them all. 

By the time these discussions here were held there was still 2G, 2G+ etc as regulations going on. 
Now, we have IfSG and it's still a mess to perfectly represent what needs to be renewed. 

Yes, we can identify the certificates and we can tell whether it is a test, a recovery or a vaccination certificate. But, if you start drawing the tree of possibilities that a user can have as certificate combination, it becomes very complex to code all this logic. 

Therefore we try to be as generic as possible:
1  - we check all vaccinations, the highest one e.g. 3/3 > 2/2 can be renewed (if < 90 days after technical expiration)
2 - we check all recoveries, the latest one can be renewed ( if < 90 days after technical expiration)

I hope this information helps you, even though its a bit late now.

**Comment by adeuring** [comment]
> Hello everyone, thanks for your feedback and lively discussions here! We do care about simplicity and usability. However, unfortunatelly, we also have time & cost constraints and need to deal with often changing requirements. Therefore, we try to hard code as little app logic as possible, so that we are more flexible when it comes to changing requirements in the future.
> 
> We discussed the options we have on messages to be displayed very detailed and agreed, that there are just too many options to cover them all.

Well... Meanwhile the issue is fixed in a more or less reasonable way: 
![IMG_0419](https://user-images.githubusercontent.com/6950346/213267746-21418a4c-d309-4c0b-9b23-d7efbef98ad7.JPG)

(The phrase "da es für den Nachweis Ihres Immunschutzes nicht mehr relevant ist" is a bit too handwavy for my taste though. But after all the app now tells me which certificates I can renew and which I can't renew.)

Regarding time constraints: The fact that a certificate renewal would be necessary was obvious when the first certificates were issued. In other words, you had an _entire year_ or more to implement everything.

> By the time these discussions here were held there was still 2G, 2G+ etc as regulations going on. Now, we have IfSG and it's still a mess to perfectly represent what needs to be renewed.

I understand the difficulties to implement a bunch of often changing rules that differ from state to state. But this issue is about the _core purpose_ of the Covpass app: Making the Covid vaccination certificates "manageable" on a smartphone. And the rules when a vaccination certificate expires and if it can or should be renewed are not that difficult. And they did never change, as far as I know. And, as mentioned above, the issue has been fixed meanwhile...

I am certainly not the only one who was repeatedly nagged by the Covpass app in April/May 2022 that the vaccination certificates would expire soon but that they could be renewed "really soon". When I then updated the app to the version that was supposed to allow the renewal but noticed that the renewal does not work, I felt, well, "verarscht". You caused a lot of absolutely unnecessary work for the people from the Covpass hotline, who had to answer the question "why doesn't the cert renewal work for me?" countless times, and you let a considerable number of people waste their time calling the hotline. 

> 
> Yes, we can identify the certificates and we can tell whether it is a test, a recovery or a vaccination certificate. But, if you start drawing the tree of possibilities that a user can have as certificate combination, it becomes very complex to code all this logic.

Does the expiry and possible or impossible renewal of vaccination certificates depend in any way on recovery/test certificates or 2G/2G+/3G rules?

> 
> Therefore we try to be as generic as possible: 1 - we check all vaccinations, the highest one e.g. 3/3 > 2/2 can be renewed (if < 90 days after technical expiration) 2 - we check all recoveries, the latest one can be renewed ( if < 90 days after technical expiration)
> 
> I hope this information helps you, even though its a bit late now.

Well, I'm drawing my conclusions... IMHO, a simple apology for the mess would have been more appropriate.
