### ISSUE TITLE
Release APK

### ISSUE THREAD

**Issue by mindbreaker** [Digitaler-Impfnachweis/covpass-android#28]
Is it possible to provide the APK Files in the releases. Sometimes you want to use an old apk.

**Comment by blizzz** [comment]
I am on SailfishOS and since there is of course no official app for it, i was looking to get the android app and hope it works with thw compatibility layer. But the app is neither available on fdroid nor Aurora store. Please, at least publish the apk here.

**Comment by obfusk** [comment]
FWIW: I've heard (but not tested this myself) that -- now that Switzerland and the EU decided to recognise each other's covid certificates -- EU citizens can use the Swiss covid app -- which is available via F-Droid -- by importing/scanning a QR code, which one can usually obtain via a website.

**Comment by axtimwalde** [comment]
My Google account is in the US. Traveling in Germany, I had to learn that the app is not available in my country. This is silly. Please release the APK here.

**Comment by olof-nord** [comment]
Thanks for the tip @obfusk! Until https://github.com/Digitaler-Impfnachweis/covpass-android/issues/2 is resolved, I will use the "Covid Cert" Swiss covid app from F-Droid.

**Comment by axtimwalde** [comment]
@HamletDuFromage has an open PR with an APK of this demo-version https://github.com/Digitaler-Impfnachweis/covpass-android/pull/37 that worked great for me. Thanks a lot! Would be good to have an official release though.

**Comment by jleufgen** [comment]
Hello, it was decided against providing the Android packages (APK) to certain websites for their publication. Best regards

**Comment by blizzz** [comment]
> Hello, it was decided against providing the Android packages (APK) to certain websites for their publication. Best regards

Ok. What are the suggested solutions to the problems listed here?

**Comment by axtimwalde** [comment]
Interesting @jleufgen. Can you please elaborate what the derogatory "certain websites" comment has to do with this issue? This issue did not ask to distribute an APK to any website but your own official website instead of relying on the commercial gate keeper Google. How are you planning to address the technical issues for German citizens living abroad as raised in this thread?

**Comment by github-tomster** [comment]
@axtimwalde 
enjoy the silence!
it makes no sense to think an upper-level federal agency can handle such a project 🤡

**Comment by andycandy-de** [comment]
Could you please explain the reason(s) of the decision? Why do you force the community to use commercial app stores. We just want an official, open source to download the official release apk. Just attach it to the GIT Tag and put a download link to the homepage. What's the problem with that? I really don't understand this.

**Comment by olof-nord** [comment]
The approach taken is a farce. This shows how "digitalisation" in Germany is just a joke. Sorry, but this isn't hard to set up.

**Comment by github-tomster** [comment]
fun fact:
it is our fault because we as the people made our choice and our taxes pay this party here! 💸 
this is all a joke 🤡

**Comment by axtimwalde** [comment]
Let's tone it down and keep the issue where it is. Germany is not doing so badly at Digitalisation these days. (1) These apps exists, and it's open source, we can just build it. (2) digital certificates for vaccination, testing, and recovery status exist and work. (3) you can get tested.  All things that do not work in other places like e.g. the US.  The issue here is that they introduced a firewall of uninformed outreach staff to shield the developers from hard to filter open source community noise and and that leads to this creeping in of bureaucracy and closing of real issues.  I suggest to reopen the issue with a clear description of the problem as soon as it is being closed.  Keep the tone professional at each reopening and still explain the situation again: German citizens living outside of the EU cannot currently install this important app without building it themselves, this is not ok.  I stopped reiterating this because I have an installation from a community build and it works as it should.  It can also be nice to involve Twitter or other public places but please without the unjustified insults ;).

**Comment by axtimwalde** [comment]
Oh I also just checked the Google App store again and the app is no available in the US store. This solves the issue for me. Would still be cool to have the APKs available outside of commercially walled gardens.

**Comment by github-tomster** [comment]
@axtimwalde 
okay let us pretend it is 1981. thank you!
i feel much better and safer now, problem solved 🤦🏻‍♂️

**Comment by x51mon** [comment]
@axtimwalde Well its just sad because it'd be such a simple thing to do. It can be automated and shouldn't take much effort to set up. I don't see any disadvantage for them, most people would still download it through PlayStore anyway.

Germany is doing bad at digitalisation in some areas, but here, I think, it is neither a lack of knowledge or resources, they just don't want to for some reason, which makes it so frustrating. Especially since they didn't give any explanation.

But I agree to keep the tone nice.
