### ISSUE TITLE
CovpassCheck shows valid certificates as invalid if "full vaccination" status is not reached yet

### ISSUE THREAD

**Issue by AndiPopp** [Digitaler-Impfnachweis/covpass-android#49]
The first time I used the CovPassCheck app I got a negative result saying "full vaccination" status is not reached. Everything worked as intended IMO.

I tried to demonstrate this to my friend today and got a negative result saying the certificate was invalid. Testing with my father's certificates I found out, that certificates are shown as invalid if the "full vacination" status has not been reached. 

I suppose this is a bug, since the app originally gave a more helpful answer, as does the CovPass app. If not, may I suggest to add the hint that the "full vaccination" status has not been reached as possible reason for the result?

(Also discussed in https://github.com/Digitaler-Impfnachweis/covpass-android/discussions/47)

**Comment by timokoenig** [comment]
Also similar to this issue https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/34

It is a data privacy question. The better the error message in the CheckApp, the more personal information get exposed to another person. After we added recovery certificates we do not want to expose the information if you are recovered or vaccinated. That resulted in a very generic error screen that doesn't give away those information.

**Comment by AndiPopp** [comment]
I see the data privacy issue, even though one could argue the result screen of the CovPassCheck app is probably the least effective data protection layer. 

The other issue is that the current negative result screen still shows misleading information. My first reaction to this result would be to assume my certificate is somehow corrupt and I need to get a new one.

The solution to just add a third reason to the negative result screen adresses all the issues, does it not? I.e. instead of the current list of possible reasons (as of v1.28.4):
- Certificate invalid
- Technical Problems

it should show:
- Certificate invalid
- Vaccine protection incomplete
- Technical Problems

The person checking another person's status still cannot determine the exact reason for the negative result from the result screen, but people checking their own certificates will be informed that incomplete vaccination status is a possible reason.

**Comment by timokoenig** [comment]
Well, when you open the CovPass app you immediately see that you don't have a full immunization yet. The card has a different color and it says it right above the QR code that you would show to the other person. But I get what you're saying. I will take this to the team and discuss possible solutions

**Comment by abrock** [comment]
Perhaps there could be a distinction between codes with valid signature but not yet full immune status and technical errors like invalid signature or unreadable code.
Just displaying "The code is readable and the signature is valid but the person is not yet considered immune" doesn't reveal if the immunity comes from infection or vaccination or both and it clearly states that the problem is not that the code is smudged / unreadable.

**Comment by timokoenig** [comment]
@abrock that's a good idea

**Comment by My1** [comment]
> It is a data privacy question. The better the error message in the CheckApp, the more personal information get exposed to another person. After we added recovery certificates we do not want to expose the information if you are recovered or vaccinated. That resulted in a very generic error screen that doesn't give away those information.

well it could be just generalised as immunization cert and especially if the guidelines change and the cert owner didnt have that update yet (or just has a paper qr code and thereby might not even know the exact regulations).

it could still say that the cert has expired or immunization is not achieved before x days passed, or obviously if revocation has to occur due to things like this:
https://www.heise.de/news/Apotheken-Wie-Sicherheitsforscher-das-Impfzertifikats-Portal-kompromittierten-6145902.html

it might also be nice to tell that the user just needs to get a new cert.

some good error messages could be

* not even a certificate (e.g. wrong qr code or tech issues)
* a certificate in nature but not a valid signature in the first place (e.g. sample cert)
* revoked signing key (e.g. due to compromised issuer -> tell user to get a new certificate)
* needs additional vaccines (e.g. the first cert of a biontech)
* needs extra time
* expired (most notably on test certificates)



> I see the data privacy issue, even though one could argue the result screen of the CovPassCheck app is probably the least effective data protection layer.

this. the data is in the qr code (I assume) so there isnt too much hiding it anyway as people could likely if they REALLY want pipe the data via some other scanner and get the data if they want.

**Comment by abrock** [comment]
> revoked signing key (e.g. due to compromised issuer -> tell user to get a new certificate)

**Comment by abrock** [comment]
> revoked signing key (e.g. due to compromised issuer -> tell user to get a new certificate)

I think it's highly unlikely that those responsible will ever admit that no existing certificate issued by a pharmacy is trustworthy, so the revoked key scenario is unlikely.

**Comment by My1** [comment]
> I think it's highly unlikely that those responsible will ever admit that no existing certificate issued by a pharmacy is trustworthy, so the revoked key scenario is unlikely.

well security researchers have proven that it wasnt too hard to get into the system and act as a pharmacy.

not sure how many people doubt the certs made by actual pharmacies but the fact that it was possible to get in and not have seperate keys to revoke is an issue. it was "effectively trivial" to make the counterfeit documents to get recognized into the certificate system despite even an address/phone lookup would have been enough to entirely thwart the thing.

**Comment by Leseratte10** [comment]
Just joined this repo to report this exact issue (the CovPassCheck app not displaying why a QR code is invalid) - does this really not happen because of privacy concerns?

If I am verifying someone else's QR code that they show to me on their phone, and I'm supposed to scan that with the CovPassCheck app, I might as well use a Camera app and take a photo of the QR code they are showing, and then I can later decode all information about the QR code that I want. Or I run a screen recording on my phone, then it's not even visible to anyone. Or I use apps that don't tell me what I can do on my own phone, like the DGCA verifier ( https://github.com/eu-digital-green-certificates/dgca-verifier-app-android ) and just display the information from the damn QR code.
By showing another person your QR code you agree to telling them your name, DOB and when you've been vaccinated, that's the point of the QR code. 

Handling a completely invalid junk QR code the same way as a fully valid, vaccination QR code that's just a couple days before the deadline, by just showing a generic error, seems like a pretty stupid solution. All the data is in the QR code and visible to bad actors with a little bit of additional work anyways, there's no need to restrict that in such a user-unfriendly way, in my opinion.

**Comment by jleufgen** [comment]
Hi all :) The topic will be worked on in one of the next sprints. Thank you for the feedback! Best regards!
