### ISSUE TITLE
Dependency Injection vs. Service Locator

### ISSUE THREAD

**Issue by mganss** [Digitaler-Impfnachweis/covpass-android#56]
I find the section in the README about dependency injection confusing. It says:

> Koin follows the (dynamic) service locator pattern which has been criticized for a very long time.

The approach to dependency management described in the paragraphs that follow *is* the service locator pattern. Key to dependency injection is the injection part.

In the current implementation, there is a tight coupling to the `*Deps` service locator objects (`sdkDeps`, `covpassDeps` etc.). Objects "pull" their dependencies from these service locator objects.

I'm not criticizing the use of the service locator pattern and I'm sure it works well here.

**Comment by wkornewald** [comment]
You're focusing on the central object aspect, but this is just a minor aspect of the whole solution.

Most articles about the service locator pattern discuss a dynamic version which is more like a runtime registry (like Koin) or at least has runtime-based lookups. This is why the text also says "(dynamic)". The criticism and problems stem from this very dynamic nature which doesn't even provide the most basic compile-time guarantees and often leads to craches for trivial reasons like a missing dependency.

Our DI could also be called some kind of service locator from the "central object" aspect, but it follows a very static definition & lookup approach which leads to completely different properties that I wouldn't even want to use the same name for it because it only leads to confusion.

**Comment by wkornewald** [comment]
I hope it's ok if I close this since our DI really has nothing to do with the Koin approach?

**Comment by mganss** [comment]
First up, I'm not questioning the implementation in this project nor do I have an issue with any of the specific libraries discussed (I had never heard of Koin, Dagger, or Hilt before 🤷🏻). Neither am I advocating against applying the service locator pattern.

> You're focusing on the central object aspect, but this is just a minor aspect of the whole solution.

My intention was to focus on the distinction between the service locator pattern (be it static, dynamic, or whatever flavor) and the dependency injection pattern (pull vs. push). The implementation in this project simply does not use dependency injection, it uses the service locator pattern.

> Most articles about the service locator pattern discuss a dynamic version which is more like a runtime registry (like Koin) or at least has runtime-based lookups. This is why the text also says "(dynamic)". 

Do they? 

Here's the section in the Android Developer's "Best Practices" docs about service locator: https://developer.android.com/training/dependency-injection#di-alternatives

The example given is a static implementation.

Here's an article by Martin Fowler from 2004: https://martinfowler.com/articles/injection.html#UsingAServiceLocator

The service locator he describes initially is a static one. Later, he goes on to discuss a dynamic variant he calls "dynamic service locator".

> The criticism and problems stem from this very dynamic nature which doesn't even provide the most basic compile-time guarantees and often leads to crashes for trivial reasons like a missing dependency.

AFAICT the two major criticisms of service locator are:
1. The dependencies of a class are not visible on its API surface
2. The service locator itself becomes a redundant dependency for every class using it

See for example:
- The [aforementioned article](https://developer.android.com/training/dependency-injection#di-alternatives) on Android Developer docs
- [The Service Locator Anti-Pattern](https://freecontent.manning.com/the-service-locator-anti-pattern/)
- The series of articles by Mark Seeman: [Service Locator is an Anti-Pattern](https://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/), [Service Locator violates SOLID](https://blog.ploeh.dk/2014/05/15/service-locator-violates-solid/), and [Service Locator violates encapsulation](https://blog.ploeh.dk/2015/10/26/service-locator-violates-encapsulation/)

Both of these characteristics are present in your implementation (not saying this is bad per se). Number 2 is obvious, let's look at number 1. 

What are the dependencies of [`GroupedCertificates`](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/3b95b05221e8108ea8cc3cb8e4268a5c1af124a6/covpass-sdk/src/main/java/de/rki/covpass/sdk/cert/models/GroupedCertificates.kt)? Not visible from its API. You'll have to dig into the implementation of `getMainCertificate()` to see that it takes a dependency on `sdkDeps.clock`.

Interestingly, there are other classes like [`ValidityCheckViewModel`](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/cefe54f2a18ca6a0f971f75b545cba64aedffc2b/common-app-covpass/src/main/java/de/rki/covpass/app/validitycheck/ValidityCheckViewModel.kt) that expose their dependencies in the constructor (but defaulting to values pulled from the service locator, giving the impression that they are not actually dependencies):

https://github.com/Digitaler-Impfnachweis/covpass-android/blob/cefe54f2a18ca6a0f971f75b545cba64aedffc2b/common-app-covpass/src/main/java/de/rki/covpass/app/validitycheck/ValidityCheckViewModel.kt#L27-L33

This might become a maintenance issue because now you have two alternative ways of dependency resolution.

BTW [this commit](https://github.com/Digitaler-Impfnachweis/covpass-android/commit/a9727671aa8cc0597f84fb6827022eb558da278a) already hints at issues with the current service locator approach (couldn't find #194 which is mentioned in the commit message, is that in a different repo?).

> Our DI could also be called some kind of service locator from the "central object" aspect, but it follows a very static definition & lookup approach which leads to completely different properties that I wouldn't even want to use the same name for it because it only leads to confusion.

The main distinction between DI and SL is the direction of dependency resolution and IMO it leads to much greater confusion calling something dependency injection where no actual ***injection*** is taking place.

Apologies for this having become a little rantish 😔

**Comment by wkornewald** [comment]
The distinction between service locator and DI is a little bit hairy at the edge, especially where the framework / hollywood pattern takes over. At the outer layers (e.g. Fragment) you have to use Koin's `get()` or Hilt/Dagger annotations or `myDeps.something` which is more or less like accessing a service locator. But from that perspective every DI solution becomes pull-based and tightly coupled.

The question is: Are the classes instantiated by `*Deps` using the service locator pattern or is that DI? And here it's clearly push-style / DI. `DscRepository`, `CertValidator`, etc. all are using the push pattern and not the service locator pattern.

Now the edge could have been limited to the Fragment layer, but we chose the ViewModel constructor (only the ctor) via default args because that reduces boilerplate while still allowing to inject (push-style) deps in unit tests or subclasses or for composition. So, it's actually some kind of hybrid between push and pull style and it offers the whole flexibility of DI and the coupling is loosened to the point where it becomes irrelevant in practice.

Finally, global functions or functions defined on data do indeed sometimes deviate from the primary pattern, again for boilerplate reasons and/or to emphasize the data aspect (e.g. for GroupedCertificates). These are the biggest exceptions to the rule.

So, even if you've found a few exceptions to our primary DI pattern, it still is DI and not service locator. Our DI just allows switching from push to pull in rare cases and for valid reasons where the risks that come with tight coupling are very low.

However, you're right that Koin is not exactly the service locator pattern itself, but a DI solution with dynamic lookups. In case of the service locator a lot of criticism goes against the dynamic nature and I wanted to reuse that criticism against Koin. So that particular wording could be improved, though I'm not sure about how to reword it without adding lots of explanatory text...

> BTW [this commit](https://github.com/Digitaler-Impfnachweis/covpass-android/commit/a9727671aa8cc0597f84fb6827022eb558da278a) already hints at issues with the current service locator approach (couldn't find #194 which is mentioned in the commit message, is that in a different repo?).
> 

That commit was only fixing what was implemented too quickly due to time pressure. There also wasn't actually any issue apart from me wanting to reinforce the pattern. The commit history esp. from June is not helpful for this discussion. ;)

**Comment by wkornewald** [comment]
I had another look at the GroupedCertificates and the deps access was even completely unnecessary. It'll be removed in all the time `.now()` function calls soon. (well it's not completely gone because the java time lib still uses the service locator pattern internally to fetch the current system time zone)

**Comment by wkornewald** [comment]
Oh and your ticket started a discussion about making it more difficult and more in-your-face when accessing the deps directly.
